#!/bin/sh
################################
#			╔╗ ╔═╗╔═╗╦ ╦╔═╗		#
#			╠╩╗╚═╗╠═╝║║║╠═╝		#
#			╚═╝╚═╝╩  ╚╩╝╩  		#
#			- By: Areia -		#
################################

# ##############################################################################
# #                          ENV VARS BY RXYHN                                 # 
# ##############################################################################

## Environments
export PATH="${PATH}:${HOME}/.config/bspwm/bin"

# Parse colors from "~/.Xresources"
xrdb -override "${HOME}/.Xresources"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

# ##############################################################################
# #                             GENERAL SETTINGS                               #
# ##############################################################################

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

CURRENT_BORDER='2.5'
CURRENT_GAP='19'
CURRENT_SRATIO='1.4'

#bspc config border_width         2
#bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Run EWW.
#$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Start X wallpaper.
feh --no-fehbg --bg-fill ~/backgrounds/aphrodite.png 

# Fix cursor.
xsetroot -cursor_name left_ptr 

# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &
